/**
 *
 *  login.cc
 *  This file is generated by drogon_ctl
 *
 */

#include "login.h"
#include <string>

using namespace api::v1;

void login::doLogin(const HttpRequestPtr &req,
                   std::function<void(const HttpResponsePtr &)> &&callback)
{
    auto json = req->getJsonObject();
    Json::Value ret;

    if (json)
    {
        auto clientPtr = drogon::app().getFastDbClient("arth");
        // clientPtr->execSqlAsync(
        //     "select * from users where org_name=$1",
        //     [](const Result &r) {
        //         std::cout << r.size() << " rows selected!" << std::endl;
        //         int i = 0;
        //         for (auto row : r)
        //         {
        //             std::cout << i++ << ": user name is " << row["user_name"].as<std::string>() << std::endl;
        //         }
        //     },
        //     [](const DrogonDbException &e) {
        //         std::cerr << "error:" << e.base().what() << std::endl;
        //     },
        //     "default");
    }

    auto resp = HttpResponse::newHttpJsonResponse(ret);
    callback(resp);
}
